sonar.projectKey=mobile-app-roomies_front-end-roomies
sonar.organization=mobile-app-roomies
sonar.projectName=Front-End Roomies
sonar.sources=app,components,contexts,hooks,lib,constants
sonar.tests=__tests__,**/__tests__
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.expo/**,**/assets/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml
